version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - "3030:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend  # Wait for the backend to be ready before starting
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://abel:hehe@db:5432/documentation_enrichment
      - EMAIL_USER=abel.kristanto1@gmail.com
      - PASSWORD_USER=z9kk79v4w3
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: abel
      POSTGRES_PASSWORD: hehe
      POSTGRES_DB: documentation_enrichment
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
