FROM node:16 AS dev

WORKDIR /app

# COPY ./frontend/package.json ./frontend/package-lock.json ./

COPY ./frontend ./
RUN npm install
RUN npm install -g vite --save-dev
RUN npm install vite --save-dev
RUN npm i -g --save-dev @types/node

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
