version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev # Use a separate Dockerfile for development
    ports:
      - "3000:5173" # Change this to match the port Vite uses in development
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessary for some environments to detect file changes
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
